using CSFFModFramework.Util;

namespace CSFFModFramework.Api;

/// <summary>
/// Semantic-name → vanilla GUID registry (Centralization Tier 1, P7). Replaces the
/// hardcoded GUID sets every content mod maintains (ACT LargeTreeGuids/LitFireGuids,
/// Sirus food/water lists, H&amp;F Turnroot/Pouch constants, WDI soil GUIDs) — those
/// break silently on game updates; this table is regenerated from extracted game data.
///
/// <para>Backed by an embedded resource (<c>Resources/VanillaIds.json</c>) generated by
/// <c>Development_Tools/Generate-VanillaIds.ps1</c> from
/// <c>Documentation/GameData/CSFF-JsonData_&lt;version&gt;/UniqueIDScriptableGUID/</c>.
/// Regenerate on every game-data extraction (wired into /extract-latest-carddata).</para>
///
/// <code>
/// string stoneGuid = VanillaIds.Get("Stone");
/// foreach (var fireUid in VanillaIds.Fires) { ... }
/// </code>
/// </summary>
public static class VanillaIds
{
    private static bool _loaded;
    private static string _gameVersion = "";
    private static Dictionary<string, string> _cards;
    private static Dictionary<string, string> _stats;
    private static Dictionary<string, IReadOnlyList<string>> _groups;
    private static readonly IReadOnlyList<string> Empty = Array.Empty<string>();

    /// <summary>Game version token the embedded table was generated from (e.g. "EA_0-64f").</summary>
    public static string GameVersion { get { EnsureLoaded(); return _gameVersion; } }

    /// <summary>Number of card names in the registry. 0 if the embedded table failed to load.</summary>
    public static int CardCount { get { EnsureLoaded(); return _cards?.Count ?? 0; } }

    // ── Card lookups ─────────────────────────────────────────────────────────

    /// <summary>GUID for a vanilla CardData by its asset name (e.g. "Stone", "MetalNugget"). Null if unknown.</summary>
    public static string Get(string cardName)
    {
        EnsureLoaded();
        return !string.IsNullOrEmpty(cardName) && _cards != null
            && _cards.TryGetValue(cardName, out var guid) ? guid : null;
    }

    /// <summary>Try-get variant of <see cref="Get"/>.</summary>
    public static bool TryGet(string cardName, out string guid)
    {
        guid = Get(cardName);
        return guid != null;
    }

    // ── Stat lookups ─────────────────────────────────────────────────────────

    /// <summary>
    /// GUID for a vanilla GameStat by name with CJK annotation stripped
    /// (e.g. "Skill_Crafting", "Satiation"). Null if unknown.
    /// </summary>
    public static string GetStat(string statName)
    {
        EnsureLoaded();
        return !string.IsNullOrEmpty(statName) && _stats != null
            && _stats.TryGetValue(statName, out var guid) ? guid : null;
    }

    /// <summary>Try-get variant of <see cref="GetStat"/>.</summary>
    public static bool TryGetStat(string statName, out string guid)
    {
        guid = GetStat(statName);
        return guid != null;
    }

    // ── Curated semantic groups ──────────────────────────────────────────────

    /// <summary>GUID list for a curated group by name. Empty list if the group is unknown.</summary>
    public static IReadOnlyList<string> Group(string groupName)
    {
        EnsureLoaded();
        return !string.IsNullOrEmpty(groupName) && _groups != null
            && _groups.TryGetValue(groupName, out var list) ? list : Empty;
    }

    /// <summary>Large tree variants (TreeLargePine/Oak/Birch/Willow).</summary>
    public static IReadOnlyList<string> LargeTrees => Group("LargeTrees");

    /// <summary>All vanilla cooking-fire cards, lit + extinguished variants.</summary>
    public static IReadOnlyList<string> Fires => Group("Fires");

    /// <summary>Open-storage containers (Basket, Shelf, Sack, DryingRack, ...) raid-able by wildlife.</summary>
    public static IReadOnlyList<string> OpenStorage => Group("OpenStorage");

    /// <summary>Water containers animals can drink from: ClayBasin, WateringTrough, RainCistern (large) + ClayBowl, ClayJar, CopperBottle, CopperJar, WaterskinWaterProofed_ (portable).</summary>
    public static IReadOnlyList<string> WaterSources => Group("WaterSources");

    /// <summary>Carnivore-edible foods: meats, fish, bones.</summary>
    public static IReadOnlyList<string> AnimalFoods => Group("AnimalFoods");

    /// <summary>Wildlife bear combat encounter event cards.</summary>
    public static IReadOnlyList<string> BearEncounters => Group("BearEncounters");

    // ── Loading ──────────────────────────────────────────────────────────────

    private const string ResourceName = "CSFFModFramework.Resources.VanillaIds.json";

    private static void EnsureLoaded()
    {
        if (_loaded) return;
        _loaded = true;
        try
        {
            using var stream = typeof(VanillaIds).Assembly.GetManifestResourceStream(ResourceName);
            if (stream == null)
            {
                Log.Warn($"[VanillaIds] embedded resource '{ResourceName}' not found — registry empty.");
                return;
            }
            using var reader = new StreamReader(stream, System.Text.Encoding.UTF8);
            var json = reader.ReadToEnd();
            if (MiniJson.Parse(json) is not Dictionary<string, object> root)
            {
                Log.Warn("[VanillaIds] embedded table failed to parse — registry empty.");
                return;
            }

            _gameVersion = root.TryGetValue("GameVersion", out var gv) ? gv as string ?? "" : "";
            _cards = ReadStringMap(root, "Cards");
            _stats = ReadStringMap(root, "Stats");

            _groups = new Dictionary<string, IReadOnlyList<string>>(StringComparer.OrdinalIgnoreCase);
            if (root.TryGetValue("Groups", out var g) && g is Dictionary<string, object> groupsDict)
            {
                foreach (var kvp in groupsDict)
                {
                    if (kvp.Value is not List<object> rawList) continue;
                    var list = new List<string>(rawList.Count);
                    foreach (var item in rawList)
                        if (item is string s && !string.IsNullOrEmpty(s)) list.Add(s);
                    _groups[kvp.Key] = list;
                }
            }

            Log.Debug($"[VanillaIds] loaded {_cards?.Count ?? 0} cards, {_stats?.Count ?? 0} stats, "
                    + $"{_groups.Count} groups (game data {_gameVersion}).");
        }
        catch (Exception ex)
        {
            Log.Warn($"[VanillaIds] load failed: {Log.ExceptionText(ex)}");
        }
    }

    private static Dictionary<string, string> ReadStringMap(Dictionary<string, object> root, string key)
    {
        var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (root.TryGetValue(key, out var v) && v is Dictionary<string, object> dict)
            foreach (var kvp in dict)
                if (kvp.Value is string s && !string.IsNullOrEmpty(s))
                    map[kvp.Key] = s;
        return map;
    }
}
