global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using BepInEx;
global using HarmonyLib;
global using UnityEngine;
global using mod_update_manager;
