using System;
using System.Collections;
using System.Linq;
using System.Reflection;
using BepInEx.Logging;
using CSFFModFramework.Api;
using CSFFModFramework.Util;

namespace Sirus23ModCollection.Patcher
{
    /// <summary>
    /// Wild Fox NPC lookup + tame-retirement helpers for <see cref="CompanionHuntPatch"/> — the
    /// Fox-specific twin of <see cref="WildOwlLifecyclePatch"/>, following the exact same M2-shrunk
    /// shape: the Fox's death/respawn lifecycle (5-day kill respawn, dawn/dusk window relocation,
    /// run-start reconciliation) is generated by the framework from <c>Animals/Fox.json</c>
    /// (ActivityWindow + Spawn.DeathRespawnTicks/SuppressWhileCardOnBoard/SuppressedRespawnTicks)
    /// and executed by the framework's <c>AnimalLifecycleTicker</c>. What remains here is only
    /// what the M6 tame flow (CompanionHuntPatch's "Attempt to Tame" AfterWrapped hook) still
    /// needs until Phase 5 ports it into the framework — see WildOwlLifecyclePatch's doc comment
    /// for the full mechanism rationale (move-before-drop race, interactivity-gap fix).
    ///
    /// Duplicated per-species rather than shared with WildOwlLifecyclePatch, matching this mod's
    /// own established convention (CompanionHuntPatch keeps Wolf/Fox/Owl handlers separate rather
    /// than genericized) and avoiding a scope-creeping refactor of the already-shipped Owl file.
    ///
    /// All NPCAgent/NPCStat access here is via reflection rather than compile-time InGameNPC/
    /// NPCStat types — this mod's Assembly-CSharp reference is the nstrip build (CLAUDE.md
    /// §Harmony Patching Pitfalls: nstrip field renames cause MissingFieldException).
    /// </summary>
    internal static class WildFoxLifecyclePatch
    {
        private const string FoxAgentUid = "wildfox_agent";

        private static ManualLogSource Logger => Plugin.Logger;
        private static object _npc;

        public static void Register()
        {
            SubscribeToGmInitialized();
        }

        /// <summary>
        /// Clears the cached InGameNPC at every run start — see WildOwlLifecyclePatch's identical
        /// method for the full rationale (a stale reference from a prior run breaks the tame
        /// CardPredicate match for the new run's fox).
        /// </summary>
        private static void SubscribeToGmInitialized()
        {
            try
            {
                var asm = AppDomain.CurrentDomain.GetAssemblies()
                    .FirstOrDefault(a => a.GetName().Name == "Assembly-CSharp");
                var gmType = asm?.GetType("GameManager");
                var field = gmType?.GetField("OnGMInitialized",
                    BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
                if (field == null || field.FieldType != typeof(Action))
                {
                    Logger?.LogDebug("[WildFoxLifecycle] GameManager.OnGMInitialized not found — NPC cache will not reset between runs");
                    return;
                }
                var existing = (Action)field.GetValue(null);
                field.SetValue(null, (Action)Delegate.Combine(existing, (Action)OnGameManagerInitialized));
                Logger?.LogDebug("[WildFoxLifecycle] subscribed to OnGMInitialized for NPC cache reset");
            }
            catch (Exception ex)
            {
                Logger?.LogError($"[WildFoxLifecycle] SubscribeToGmInitialized failed: {ex.InnerException?.ToString() ?? ex.ToString()}");
            }
        }

        private static void OnGameManagerInitialized()
        {
            _npc = null;
        }

        // ── NPC/stat lookup (reflection-only — see class doc comment) ───────────

        /// <summary>Exposes the cached Wild Fox InGameNPC for CompanionHuntPatch's post-tame
        /// retirement (stat write + immediate relocation).</summary>
        internal static bool TryGetFoxNpc(out object npc)
        {
            bool found = TryResolveNpc();
            npc = found ? _npc : null;
            return found;
        }

        private const string SpiritWorldUid = "db69b1711fb0190419ce0c5466591772";
        private static object _spiritWorldCard;
        private static ConstructorInfo _envIdCtor;
        private static MethodInfo _moveNpcMethod;

        /// <summary>
        /// Directly relocates the Wild Fox to the Spirit World via GameManager.MoveNPC instead of
        /// waiting for the engine's own next UpdatePassiveEffects/CheckForActions pass to fire
        /// WildFox_ExistsZero_SpiritWorld — see WildOwlLifecyclePatch.TryRelocateToSpiritWorldNow
        /// for the full interactivity-gap rationale (identical mechanism, Fox-independent).
        /// </summary>
        internal static bool TryRelocateToSpiritWorldNow(object npc)
        {
            try
            {
                var gm = CardUtil.GetGameManagerInstance();
                if (gm == null)
                {
                    Logger?.LogDebug("[WildFoxLifecycle] TryRelocateToSpiritWorldNow: GameManager instance unavailable");
                    return false;
                }

                if (_spiritWorldCard == null || _envIdCtor == null || _moveNpcMethod == null)
                {
                    var asm = AppDomain.CurrentDomain.GetAssemblies()
                        .FirstOrDefault(a => a.GetName().Name == "Assembly-CSharp");
                    var uidType = asm?.GetType("UniqueIDScriptable");
                    var cardDataType = asm?.GetType("CardData");
                    var envIdType = asm?.GetType("EnvID");
                    var getFromId = uidType?.GetMethods()
                        .FirstOrDefault(m => m.Name == "GetFromID" && m.IsGenericMethodDefinition);
                    if (getFromId == null || cardDataType == null || envIdType == null)
                    {
                        Logger?.LogDebug($"[WildFoxLifecycle] TryRelocateToSpiritWorldNow: type resolution failed (getFromId={getFromId != null}, cardDataType={cardDataType != null}, envIdType={envIdType != null})");
                        return false;
                    }

                    _spiritWorldCard ??= getFromId.MakeGenericMethod(cardDataType).Invoke(null, new object[] { SpiritWorldUid });
                    if (_spiritWorldCard == null)
                    {
                        Logger?.LogDebug($"[WildFoxLifecycle] TryRelocateToSpiritWorldNow: Spirit World CardData lookup for '{SpiritWorldUid}' returned null");
                        return false;
                    }

                    _envIdCtor ??= envIdType.GetConstructor(new[] { cardDataType, typeof(bool) });
                    _moveNpcMethod ??= gm.GetType().GetMethod("MoveNPC", BindingFlags.Public | BindingFlags.Instance);
                    if (_envIdCtor == null || _moveNpcMethod == null)
                    {
                        Logger?.LogDebug($"[WildFoxLifecycle] TryRelocateToSpiritWorldNow: EnvID ctor or MoveNPC method not found (envIdCtor={_envIdCtor != null}, moveNpcMethod={_moveNpcMethod != null})");
                        return false;
                    }
                }

                object envId = _envIdCtor.Invoke(new object[] { _spiritWorldCard, false });
                _moveNpcMethod.Invoke(gm, new object[] { npc, envId });
                return true;
            }
            catch (Exception ex)
            {
                Logger?.LogError($"[WildFoxLifecycle] TryRelocateToSpiritWorldNow failed: {ex.InnerException?.ToString() ?? ex.ToString()}");
                return false;
            }
        }

        private static bool TryResolveNpc()
        {
            if (_npc != null) return true;

            var gm = CardUtil.GetGameManagerInstance();
            if (gm == null) return false;

            if (Reflect.GetMember(gm, "AllNPCs") is not IEnumerable allNpcs) return false;

            foreach (var npc in allNpcs)
            {
                if (npc == null) continue;
                var model = Reflect.GetMember(npc, "NPCModel");
                if (model == null) continue;
                if (Reflect.GetMember(model, "UniqueID") as string == FoxAgentUid)
                {
                    _npc = npc;
                    Logger?.LogDebug("[WildFoxLifecycle] resolved Wild Fox InGameNPC");
                    return true;
                }
            }
            return false;
        }

        internal static bool TrySetStatValue(object npc, string statUid, float value)
        {
            try
            {
                var statInstance = FindStatInstance(npc, statUid);
                if (statInstance == null) return false;
                var method = statInstance.GetType().GetMethod("SetStatValue",
                    BindingFlags.Public | BindingFlags.Instance);
                if (method == null) return false;
                method.Invoke(statInstance, new object[] { value });
                return true;
            }
            catch (Exception ex)
            {
                Logger?.LogError($"[WildFoxLifecycle] TrySetStatValue failed: {ex.InnerException?.ToString() ?? ex.ToString()}");
                return false;
            }
        }

        private static object FindStatInstance(object npc, string statUid)
        {
            if (Reflect.GetMember(npc, "NPCStatsDict") is not IDictionary dict) return null;
            foreach (DictionaryEntry entry in dict)
            {
                if (entry.Key == null) continue;
                if (Reflect.GetMember(entry.Key, "UniqueID") as string == statUid)
                    return entry.Value;
            }
            return null;
        }
    }
}
